import Footer from './components/Footer'
import Header from './components/Header'
import './globals.css'
import { Saira } from 'next/font/google'

const saira = Saira({ subsets: ['latin'],weight:'400' })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={saira.className}>
        <Header/>
        <main className='min-h-screen'>{children}</main>
        <Footer/>
      </body>
    </html>
  )
}
